services:
  backend:
    build:
      context: .
      args:
        USE_OPENVINO: "true"
    image: doresare-backend:latest
    container_name: doresare-backend
    ports:
      - "7860:7860"
    device_cgroup_rules:
      - 'c 226:* rwm'
    devices:
      - /dev/dri/renderD128:/dev/dri/renderD128
      - /dev/dri/card0:/dev/dri/card0
    env_file:
      - .env.doresare-backend
    environment:
      - GRADIO_SERVER_NAME=0.0.0.0
      - USE_OPENVINO=true
      - LIBVA_DRIVER_NAME=iHD
      - MOVIEPY_USE_GPU=true
      - MOVIEPY_FFMPEG_CODEC=h264_qsv
      - MOVIEPY_FFMPEG_PARAMS=-init_hw_device qsv=hw -filter_hw_device qsv -global_quality 25
    group_add:
      - 105
      - video
    tmpfs:
      - /tmp:size=4g
    deploy:
      resources:
        limits:
          memory: 6g
          cpus: '3.0'
        reservations:
          memory: 2g
          cpus: '0.5'
    restart: unless-stopped
    volumes:
       - ./hf_cache:/home/user/hf_cache
       - ./video_processing:/home/user/app/video_processing
